name: Autogenerate metrics-catalog.html
on: 
  push:
    paths:
      - data/primary-dataset.yml
  pull_request:
    paths:
      - data/primary-dataset.yml
jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Prepare the ruby environment
        working-directory: tools
        run: |
          gem install bundler
          bundle install
      - name: Generate metrics-catalog.html
        working-directory: tools
        run: ruby metrics_validator.rb ../data/primary-dataset.yml ../data/front-matter.md ../metrics-catalog.html
      - name: Push metrics-catalog.html to the repo
        uses: test-room-7/action-update-file@v1
        with:
          file-path: metrics-catalog.html
          commit-msg: Automtaed update of metrics-catalog.html
          github-token: ${{ secrets.GITHUB_TOKEN }}
