name: Autogenerate metrics-catalog.html
on: 
  push:
    paths:
      - data/primary-dataset.yml
  pull_request:
    paths:
      - data/primary-dataset.yml
  workflow_dispatch:

jobs:
  generate-html:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Prepare the ruby environment
        working-directory: tools
        run: |
          gem install bundler
          bundle install
      - name: Generate metrics-catalog.html
        working-directory: tools
        run: ruby metrics_validator.rb ../data/primary-dataset.yml ../data/front-matter.md ../metrics-catalog.html
      - uses: actions/upload-artifact@v3
        with:
          name: metrics-catalog.html
          path: metrics-catalog.html
          retention-days: 5
          # the metrics-catalog.html file can now be downloaded in the github UI, see docs for more info:
          # https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts
# current permissions block actions updating files
# TODO: consider https://github.com/marketplace/actions/create-pull-request instead
# (which also requires permissions)
#      - name: Push metrics-catalog.html to the repo
#        uses: test-room-7/action-update-file@v1
#        with:
#          file-path: metrics-catalog.html
#          commit-msg: Automtaed update of metrics-catalog.html
#          github-token: ${{ secrets.GITHUB_TOKEN }}
